config/routes.rb
Rails.application.routes.draw do
  get 'player/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :player
   resources :edit
   resources :delete
   resources :show
  root 'player#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
  end
  def show
  	  render plain: params[:player].inspect
  end
  def update
  end
  def create
  	  render plain: params[:player].inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player/delete.html.erb
<%= form_with scope: :delete, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :id %><br>
    <%= form.text_field :id %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/player/edit.html.erb
<%= form_with scope: :player, url: articles_player, local: true do |form| %>
  <p>
    <%= form.label :id %><br>
    <%= form.text_field :id %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/player/index.html.erb
<h1>Гравці</h1>
<%= form_with scope: :players, url: player_path, local: true do |form| %>
  <p>
    <%= form.label :nickname %><br>
    <%= form.text_field :nickname %>
  </p>

  <p>
    <%= form.label :rank %><br>
    <%= form.text_area :rank %>
  </p>

  <p>
    <%= form.label :charisma %><br>
    <%= form.text_area :charisma %>
  </p>

  <p>
    <%= form.label :wisdom %><br>
    <%= form.text_area :wisdom %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/player/show.html.erb
<%= form_with scope: :show, local: true do |form| %>
  <p>
    <%= form.label :id %><br>
    <%= form.text_field :id %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>